CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT UNIQUE, wallet_address TEXT UNIQUE, osm_username TEXT, organization_domain TEXT, verification_status TEXT DEFAULT 'user_declared', role TEXT DEFAULT 'user', created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS metadata_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), title TEXT NOT NULL, source_type TEXT NOT NULL, source_url TEXT, submission_mode TEXT DEFAULT 'Independent / Non-Esri', steward TEXT, contact TEXT, license TEXT, bbox TEXT, spatial_reference TEXT, update_frequency TEXT, tags TEXT[], description TEXT, evidence TEXT, quality_score INT DEFAULT 0, verification_status TEXT DEFAULT 'user_declared', ipfs_uri TEXT, token_id TEXT, tx_hash TEXT, created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS metadata_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), record_id UUID REFERENCES metadata_records(id), version_number INT, metadata_json JSONB, ipfs_uri TEXT, tx_hash TEXT, note TEXT, created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS rewards (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), record_id UUID REFERENCES metadata_records(id), reward_type TEXT, amount NUMERIC, status TEXT DEFAULT 'pending', tx_hash TEXT, created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS osm_reward_claims (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), osm_username TEXT, changeset_id TEXT, target_area TEXT, contribution_description TEXT, feature_count INT, quality_score INT, amount NUMERIC, status TEXT DEFAULT 'pending_review', created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS faucet_claims (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), record_id UUID REFERENCES metadata_records(id), claimant TEXT, proof TEXT, payout_memo TEXT, amount NUMERIC, status TEXT DEFAULT 'pending_admin_review', created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS dao_proposals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), record_id UUID REFERENCES metadata_records(id), title TEXT, detail TEXT, status TEXT DEFAULT 'active', for_votes INT DEFAULT 0, against_votes INT DEFAULT 0, created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), actor TEXT, event_type TEXT, item TEXT, tx_hash TEXT, amount TEXT, metadata JSONB, created_at TIMESTAMP DEFAULT now());
